extends Node

var surname = [
	"vanplug",
	"medam",
	"fighter",
	"crunkle",
	"bigglesworth",
	"lengthy",
	"logbottom",
	"frendle",
	"bagbo",
	"mac",
	"hodgepodge",
	"plankpank",
	"freld",
	"meharty",
	"finkleton",
	"mop",
	"bop",
	"bosh",
	"mccoy",
	"fornhorn",
	"hop",
	"potato",
	"mash",
	"hoop",
	"harp",
	"onk",
	"davies",
	"Williams",
	"hale",
	"face",
	"bigtoes",
	"booklet",
	"hammock",
	"poppy",
	"frelgemo",
	"man",
	"baby",
	"gherkin",
	"mercedes",
	"bees",
	"pelkrow",
	"penny",
	"spencer",
	"f",
	"haggins",
	"buttons",
	"walro",
	"bilblin",
	"hobbin",
	"elbert",
	"flibbage",
	"hotpick",
	"frongpong",
	"fleabert",
	"bert",
	"boby",
	"henge",
	"bong",
	"ermerlmahay",
	"lubbit",
	"smith",
	"jones",
	"taylor",
	"brown",
	"wilson",
	"johnson",
	"davies",
	"robinson",
	"wright",
	"thompson",
	"evans",
	"walker",
	"white",
	"roberts",
	"green",
	"hall",
	"wood",
	"jackson",
	"clarke",
	"Channel",
	"Elderflower",
	"Galahad",
	"Nudge",
	"Bevedere",
	"Paladino",
	"Boyle",
	"Grey",
	"Questoid",
	"Aynt",
	"Pustule",
	"Piranha",
	"Cheff",
	"Paul",
	"Jetdaughter",
	"Burntnuts",
	"Frasier",
	"Readi",
	"Ximinez",
	"Flutterworth",
	"Fudder",
	"Gambolputty",
	"Willsen",
	"Hudder",
	"Gwilliam",
	"McSplits",
	"Surnamekintosh",
	"Creosote",
	"Muddles",
	"Bortlesheen",
	"Furlong",
	"Cuddles",
	"McPlankton",
	"Jackson",
	"Milltops",
	"Little",
	"Bunches",
	"Sutherland",
	"Tautus",
	"Geppo",
	"Globule",
	"Monkilla",
	"Finlayson",
	"Crilly",
	"Smith",
	"Khan",
	"Docherti",
	"Flexta",
	"McForearm",
	"Lancelot",
	"Flannel",
	"Ruff",
	"Phooey",
	"Huddles",
	"Button",
	"Berenstain",
	"Detective",
	"Shortron",
	"Growth",
	"McAnimator",
	"Potamaus",
	"Pewty",
	"Poohs",
	"Powerpuff",
	"Plutotron",
	"Fruckleberry",
	"Largesse",
	"Taunter",
	"McSmith",
	"Larch",
	"Pleldoid",
	"Chopper",
	"McGregga",
	"Squirrel",
	"Caveperson",
	"McTicket",
	"Hurlong",
	]
var forename = [
	"extends",
	"krak",
	"spaggle",
	"hank",
	"nark",
	"flange",
	"gilbo",
	"trout",
	"mark",
	"clappy",
	"creggle",
	"ranch",
	"spaggle",
	"work",
	"bilge",
	"trent",
	"harold",
	"rick",
	"smeli",
	"fop",
	"janet",
	"broloci",
	"lesegne",
	"lispy",
	"old",
	"man",
	"Bram",
	"Jemble",
	"apple",
	"hardy",
	"spent",
	"trigger",
	"button",
	"hairy",
	"candle",
	"sporty",
	"fresh",
	"lip",
	"head",
	"andy",
	"jack",
	"adam",
	"sam",
	"mr",
	"leroy",
	"crop",
	"top",
	"stereo",
	"jenny",
	"grandma",
	"auntie",
	"uncle",
	"spenny",
	"amy",
	"bert",
	"nitpick",
	"bobert",
	"titania",
	"fanny",
	"swole",
	"jim",
	"pam",
	"bob",
	"bert",
	"manny",
	"rob",
	"udo",
	"kirk",
	"marty",
	"rick",
	"seb",
	"tina",
	"betty",
	"hoppy",
	"jenny",
	"james",
	"john",
	"michael",
	"william",
	"david",
	"richard",
	"joseph",
	"thomas",
	"charles",
	"christopher",
	"daniel",
	"matthew",
	"anthony",
	"donald",
	"mark",
	"steven",
	"andrew",
	"kenneth",
	"joshua",
	"george",
	"kevin",
	"brian",
	"edward",
	"ronald",
	"timothy",
	"jason",
	"jeffry",
	"ryan",
	"jacob",
	"gary",
	"nicholas",
	"eric",
	"stephen",
	"jonathan",
	"larry",
	"justin",
	"scott",
	"brandon",
	"frank",
	"benjamin",
	"gregory",
	"Sophia",
	"Dino",
	"Benjamin",
	"Human",
	"Captain",
	"Callum",
	"Sargent",
	"Karl",
	"Bingo",
	"Jackie",
	"Patsy",
	"Louis",
	"Jem",
	"Atom",
	"John",
	"Father",
	"Hilpo",
	"Inspector",
	"Ronald",
	"Oliver",
	"Jenson",
	"Frank",
	"General",
	"Huckleberry",
	"Conrad",
	"Alexanda",
	"Magilla",
	"Jerry",
	"Isabella",
	"Bogi",
	"Frankton",
	"Edweeble",
	"Conner",
	"Artur",
	"Zoot",
	"Arthur",
	"Dexta",
	"Sumuel",
	"Ammelier",
	"Genghis",
	"Biggus",
	"Jana",
	"Gwilliam",
	"Emmer",
	"Olivia",
	"Edward",
	"Charlton",
	"Harold",
	"Jain",
	"Darstard",
	"Droopy",
	"Corporal",
	"Tracy",
	"Klaus",
	"Devlin",
	"Yogi",
	"Helmut",
	"Dingo",
	"Vick",
	"Papua",
	"Jonathan",
	"Marshall",
	"Thomas",
	"Loopi",
	"Karlmondo",
	"Ava",
	"Officer",
	"Bramwell",
	"Popsy",
	"Baxter",
	"Wheelie",
	"Mia",
	"Angela",
	"Noel",
	"Mayzee",
	"Kenneth",
	"Sporty",
	"Dougal",
	"Berty",
	"Ken"
]

var facts = [
	"terrible speller",
	"can't smell",
	"hates ears",
	"hates butter",
	"loves the smell of glue",
	"doesn't recycle",
	"draws disgusting things",
	"only eats marmalade",
	"can't tell the time",
	"struggles with anger",
	"hobyist beekeeper",
	"was an owl for 3 years",
	"eats with their toes",
	"smells funny",
	"can't wait to be old",
	"guitarist",
	"basist",
	"artist",
	"pianist",
	"collects melted ice cream",
	"sleeps in a bale of hay",
	"writes upside down",
	"talks to books",
	"pretends to be a librarian",
	"always eats their veggies",
	"loves birds",
	"adores audio equipment",
	"tames badgers",
	"hoards treasure",
	"former pirate",
	"milks almonds",
	"likes to make clip clop sounds with coconuts",
	"slipper collector",
	"bites nails",
	"paints sad pictures",
	"ate their twin in the womb",
	"technically an arachnid",
	"tree keeper",
	"dungeon master",
	"full time paladin",
	"radiator enthusiast",
	"pretty cool guy",
	"peaked in primary school",
	"bat fanatic",
	"technophobe",
	"chopstic innovator",
	"has a pet cactus",
	"former prince",
	"candy sorter",
	"secretly the protagonist",
	"unsure of what to do",
	"sharp dresser",
	"invented the gherkin",
	"always whispers",
	"part time serial killer",
	"turnip launderer",
	"knows every type of cat",
	"paperback writer",
	"shouts at birds",
	"a passionate eater of fruit",
	"can eat a whole pizza without breathing",
	"invented plankton",
	"attacks Amazon delivery drivers with a cheese grater",
	"the first person to domesticate an ant",
	"owns a large collection of trousers",
	"talkative when it would be better to be quiet",
	"likes to feel in charge",
	"prefers to wear slippers",
	"afraid of dark spaces",
	"likes swimming long distances",
	"lacks a sense of rhythm",
	"definitely not to be trusted",
	"talks about people behind their backs",
	"Father in charge of the Easter bunny",
	"gregarious but isn't named Gregory",
	"doesn't require air conditioning",
	"likes to wear fabulous shirts",
	"don't look at me",
	"has wolf-like attributes",
	"a photographer of some repute",
	"lives in a cave",
	"popular with domestic penguins",
	"got a vicious streak a mile wide",
	"wears t shirts inside out",
	"a pinball wizard",
	"can only count backwards",
	"can float but only on a Monday",
	"is currently on a diet",
	"taller than the average house",
	"very diplomatic unless drunk",
	"infamous bandit",
	"unusually ticklish",
	"invades neighbouring villages as a hobby",
	"not very organised but doesn't need to be",
	"invented time travel",
	"suspiciously vegan",
	"burns the candles at both ends",
	"expert tango dancer",
	"collects bees",
	"frightened of eating spiders",
	"gives to many charities",
	"famous for inventing the letter A",
	"sympathetic to your face",
	"refuses to say the letter P",
	"is definitely not a wolf",
	"once trod on a piece of lego",
	"has only ever blinked once",
	"discovered the igloo",
	"invented Swiss cheese",
	"adventurous but easily distracted",
	"will one day invent time travel",
	"still in second grade",
	"walks with two limps",
	"sporty",
	"a chocaholic",
	"sleeps with two eyes open",
	"plays the violin badly",
	"looks great in a skirt",
	"no sense of rhythm",
	"has the emotional range of a turnip",
	"invented gravity",
	"braver than the average murderer",
	"enjoys Internet advertising",
	"famous for being infamous",
	"allergic to candle wax",
	"likes minty chocolate",
	"can only turn left",
	"vegan and proud",
	"not too proud to accept charity",
	"wears sunglasses indoors",
	"brave in the face of adversity",
	"hates people who hide in cupboards",
	"would like to complain to the manager",
	"has a nervous disposition",
	"likes to enter rooms screaming",
	"likes to hide in cupboards"
]
